<?php
/**
 * @copyright 2024-2025 Roman Parpalak
 * @license   https://opensource.org/license/mit MIT
 * @package   S2
 */

declare(strict_types = 1);

namespace S2\Cms\Config;

use S2\Cms\Framework\Exception\ConfigurationException;
use S2\Cms\Framework\StatefulServiceInterface;
use S2\Cms\Pdo\DbLayer;
use S2\Cms\Pdo\DbLayerException;

class DynamicConfigProvider implements StatefulServiceInterface
{
    /**
     * @var array<mixed>|null
     */
    private ?array $params = null;

    /**
     * @var array<mixed>
     */
    private array $boolProxies = [];

    /**
     * @var array<mixed>
     */
    private array $intProxies = [];

    /**
     * @var array<mixed>
     */
    private array $stringProxies = [];

    public function __construct(
        private readonly ?DbLayer $dbLayer = null,
        private readonly ?string  $fileName = null,
        private readonly bool     $disableCache = true,
    ) {
    }

    #[\Override]
    public function clearState(): void
    {
        $this->params = null;
    }

    /**
     * @throws DbLayerException
     */
    public function get(string $paramName): mixed
    {
        $this->ensureParamsAreLoaded();

        if (!isset($this->params[$paramName])) {
            throw new \LogicException(\sprintf('Param "%s" does not exist.', $paramName));
        }

        return $this->params[$paramName];
    }

    public function getBoolProxy(string $paramName): BoolProxy
    {
        return $this->boolProxies[$paramName] ??= new BoolProxy($this, $paramName);
    }

    public function getIntProxy(string $paramName): IntProxy
    {
        return $this->intProxies[$paramName] ??= new IntProxy($this, $paramName);
    }

    public function getStringProxy(string $paramName): StringProxy
    {
        return $this->stringProxies[$paramName] ??= new StringProxy($this, $paramName);
    }

    /**
     * @throws DbLayerException
     */
    public function regenerate(): void
    {
        if ($this->fileName === null) {
            throw new \LogicException('The callback-only configuration provider cannot regenerate a file cache.');
        }

        $config       = $this->fetchConfig();
        $this->params = $config;

        if ($this->disableCache) {
            return;
        }

        try {
            s2_overwrite_file_skip_locked(
                $this->fileName,
                "<?php\n\n// This file is automatically generated by S2. Do not edit!\n\nreturn " . var_export($config, true) . ';'
            );
            if (\function_exists('opcache_invalidate')) {
                opcache_invalidate($this->fileName, true);
            }
        } catch (\RuntimeException $runtimeException) {
            throw new ConfigurationException(\sprintf(
                'Unable to write configuration cache file to cache directory. Please make sure PHP has write access to the file "%s" in the directory "%s".',
                basename($this->fileName),
                \dirname($this->fileName)
            ), null, $runtimeException);
        }
    }

    /**
     * @throws DbLayerException
     */
    private function ensureParamsAreLoaded(): void
    {
        if ($this->params !== null) {
            return;
        }

        if ($this->fileName === null) {
            throw new \LogicException('No configuration storage has been configured.');
        }

        $data = s2_call_without_warnings(fn(): mixed => include $this->fileName);
        if (\is_array($data)) {
            $this->params = $data;
            return;
        }

        $this->regenerate();
    }

    /**
     * Get the config from the DB
     *
     * @throws DbLayerException
     * @return array<mixed>
     */
    private function fetchConfig(): array
    {
        if (!$this->dbLayer instanceof \S2\Cms\Pdo\DbLayer) {
            throw new \LogicException('No configuration database has been configured.');
        }

        return $this->dbLayer->select('name, value')
            ->from('config')
            ->execute()
            ->fetchKeyPair()
        ;
    }
}
