name: Test on MySQL

on: [ push ]

permissions:
  contents: read

env:
  DB_DATABASE: s2_test
  DB_USER: root
  DB_PASSWORD: ''
  APP_DB_TYPE: mysql

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system: ['ubuntu-22.04']
        mysql_versions:
          - 'mariadb-10.5'
          - 'mariadb-10.6'
          - 'mariadb-10.11'
          - 'mariadb-11.0'
          - 'mariadb-11.1'
          - 'mariadb-11.2'
          - 'mariadb-11.3'
          - 'mariadb-11.4'
          - 'mariadb-11.5'
          - 'mariadb-11.6'
          - '8.0'
          - '8.4'
          - '9.0'
        php_versions:
          - '8.3'
        include:
          -
            operating_system: 'ubuntu-24.04'
            php_versions: 8.3
            mysql_versions: '9.3'
          -
            operating_system: 'ubuntu-24.04'
            php_versions: 8.4
            mysql_versions: 'mariadb-11.7'
          -
            operating_system: 'ubuntu-24.04'
            php_versions: 8.5
            mysql_versions: 'mariadb-11.7'

    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shogo82148/actions-setup-mysql@62da9377d83991fce27b6ed2a397d3306121e41d # v1
        with:
          mysql-version: ${{ matrix.mysql_versions }}
          root-password: ${{ env.DB_PASSWORD }}

      - name: 'Setup MySQL'
        run: |
          mysql -e 'SELECT version();' -u${{ env.DB_USER }} -h127.0.0.1 -p${{ env.DB_PASSWORD }}

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

      - name: Run acceptance test cases
        run: ./bin/test-acceptance

      - name: Run integration test cases
        run: composer test:integration

      - name: Output logs
        if: failure()
        run: |
          find _cache/test _tests/_output/email -maxdepth 1 -type f -print -exec cat {} \;
          find _tests/_output -maxdepth 1 -type f -print
