name: Test on PostgreSQL

on: [ push ]

env:
  APP_DB_TYPE: pgsql

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system: ['ubuntu-24.04']
        php_versions:
          - '8.3'
          - '8.4'
          - '8.5'
    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@v4
      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: postgres
          password: 12345
          database: test
          port: 5432
#          postgres-version: ${{ matrix.postgres_versions }}

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

      - name: Run acceptance test cases
        run: ./bin/test-acceptance

      - name: Run integration test cases
        run: composer test:integration

      - name: Output logs
        if: failure()
        run: |
          find _cache/test _tests/_output/email -maxdepth 1 -type f -print -exec cat {} \;
          find _tests/_output -maxdepth 1 -type f -print
