name: Test on PostgreSQL

on: [ push ]

permissions:
  contents: read

env:
  APP_DB_TYPE: pgsql

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system: ['ubuntu-24.04']
        php_versions:
          - '8.3'
          - '8.4'
          - '8.5'
    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false
      - uses: ikalnytskyi/action-setup-postgres@74e396491e76c84f8ad92a4f5a69ab0deb75bbc2 # v5
        with:
          username: postgres
          password: 12345
          database: test
          port: 5432
#          postgres-version: ${{ matrix.postgres_versions }}

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

      - name: Run acceptance test cases
        run: ./bin/test-acceptance

      - name: Run integration test cases
        run: composer test:integration

      - name: Output logs
        if: failure()
        run: |
          find _cache/test _tests/_output/email -maxdepth 1 -type f -print -exec cat {} \;
          find _tests/_output -maxdepth 1 -type f -print
